version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
  rs1:
  rs2:
  rs3:

services:
  jupyterlab:
    image: jupyter/pyspark-notebook
    container_name: jupyterlab
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - localnet

  spark-master:
    image: bde2020/spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - localnet

  spark-worker-1:
    image: bde2020/spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: bde2020/spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      - localnet
  
  # Neo4j
  neo4j:
    image: neo4j:latest
    container_name: neo4j_1
    networks:
      - localnet
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./volumes/conf:/conf
      - ./volumes/data:/data
      - ./volumes/import:/import
      - ./volumes/logs:/logs
      - ./volumes/plugins:/plugins
    environment:
      - NEO4J_AUTH:neo4j/warriors
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size:4G
      - NEO4J_dbms_memory_heap_initial_size:4G
      - NEO4J_dbms_memory_heap_max__size:4G
#      - NEO4JLABS_PLUGINS='["apoc", "graph-data-science"]'
#      - apoc_import_file_enabled:true

#  mongo1:
#    image: "mongo:latest"
#    container_name: mongo1
#    command: --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
#    volumes:
#      - rs1:/data/db
#    networks:
#      - localnet
#    ports:
#      - "27017:27017"
#    restart: always

#  mongo2:
#    image: "mongo:latest"
#    container_name: mongo2
#    command: --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
#    volumes:
#      - rs2:/data/db
#    networks:
#      - localnet
#    ports:
#      - "27018:27017"
#    restart: always

networks:
    localnet:
        attachable: true
