version: "3.9"

services:
    
    namenode:
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
        ports:
            - 9870:9870
            - 9000:9000
        volumes:
            - hadoop_namenode:/hadoop/dfs/name
            - ./volumes/import:/import
        environment:
            - CLUSTER_NAME=Fontys
        env_file:
            - ./hadoop.env

    data:
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
        volumes:
            - hadoop_data:/hadoop/dfs/data
        environment:
            SERVICE_PRECONDITION: "namenode:9870"
        env_file:
            - ./hadoop.env
    
    resourcemanager:
        image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
        environment:
            SERVICE_PRECONDITION: "namenode:9000 namenode:9870 data:9864"
        env_file:
            - ./hadoop.env

    nodemanager:
        image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
        environment:
            SERVICE_PRECONDITION: "namenode:9000 namenode:9870 data:9864 resourcemanager:8088"
        env_file:
            - ./hadoop.env
        
    historyserver:
        image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
        environment:
            SERVICE_PRECONDITION: "namenode:9000 namenode:9870 data:9864 resourcemanager:8088"
        volumes:
            - hadoop_historyserver:/hadoop/yarn/timeline
        env_file:
            - ./hadoop.env
    
volumes:
    hadoop_namenode:
    hadoop_data:
    hadoop_historyserver:
