version: "3.9"

services:

    kibana:
        image: docker.elastic.co/kibana/kibana:7.12.1
        ports:
            - 8080:5601
        environment:
            ELASTICSEARCH_URL: http://client:9200
            ELASTICSEARCH_HOSTS: '["http://master:9200","http://data:9200","http://client:9200"]'
        networks:
          - elastic

    master:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        restart: always
        environment: 
            - cluster.name=Fontys
            - node.name=master
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - discovery.seed_hosts=data,client
        ports:
            - 9200:9200
        volumes:
            - ./master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - master:/usr/share/elasticsearch/data
        networks:
            - elastic

    data:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        restart: always
        environment: 
            - cluster.name=Fontys
            - node.name=data
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - discovery.seed_hosts=master,client
        ports:
            - 9201:9200
        volumes:
            - ./data.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - data:/usr/share/elasticsearch/data
        networks:
            - elastic

    client:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        restart: always
        environment: 
            - cluster.name=Fontys
            - node.name=client
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - discovery.seed_hosts=master,data
        ports:
            - 9202:9200
        volumes:
            - ./client.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - client:/usr/share/elasticsearch/data
        networks:
            - elastic

volumes:
    master:
        driver: local
    data:
        driver: local
    client:
        driver: local

networks:
    elastic:
        driver: bridge
