version: '3'
services:
  neo4j:
    image: neo4j:latest
#    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./volumes/conf:/conf
      - ./volumes/data:/data
      - ./volumes/import:/import
      - ./volumes/logs:/logs
      - ./volumes/plugins:/plugins
    environment: 
      - NEO4J_AUTH:neo4j/warriors
      # Raise memory limits
      - NEO4J_dbms_memory_pagecache_size:4G
      - NEO4J_dbms_memory_heap_initial_size:4G
      - NEO4J_dbms_memory_heap_max__size:4G
#      - NEO4JLABS_PLUGINS='["apoc", "graph-data-science"]'
#      - apoc_import_file_enabled:true 
