version: '3'
services:
  dse: # DataStax Enterprise (Apache Cassandra + Apache Spark + much more)
    image: datastax/dse-server:6.8.1
    command: [ -s -k ] # Run with Search and Analytics capabilities enabled
    environment:
      DS_LICENSE: accept # Accept licence on start
      JVM_EXTRA_OPTS: -Xmx6g -Xms6g
      SPARK_SCALA_VERSION: 2.12
      CLUSTER_NAME: Fontys
      OPSCENTER_IP: opscenter
    cap_add:
      - IPC_LOCK # Allow DSE to lock memory with mlock
    ulimits:
      memlock: -1 # Lock memory
    ports:
      - "4040:4040"
      - "7080:7080"
      - "7081:7081"
      - "8983:8983"
      - "9042:9042"
      - "9077:9077"
      - 8080:8080
      - "10000:10000"
    links:
      - opscenter
  node:
    image: datastax/dse-server:6.8.1
    command: [ -s -k ] # Run with Search and Analytics capabilities enabled
    environment:
      DS_LICENSE: accept # Accept licence on start
      JVM_EXTRA_OPTS: -Xmx6g -Xms6g
      SEEDS: dse
      CLUSTER_NAME: Fontys
      OPSCENTER_IP: opscenter
      SPARK_SCALA_VERSION: 2.12
    cap_add:
      - IPC_LOCK # Allow DSE to lock memory with mlock
    ulimits:
      memlock: -1 # Lock memory
    links:
      - dse
      - opscenter
  jupyter: # Jupyter Notebook
    build: ./customdse
    environment:
      JUPYTER_ENABLE_LAB: yes
    volumes:
      - ./jupyter:/opt/dse/jupyter:rw
    ports:
      - "8888:8888" # Exposes port to be available externally
    environment:
      PYSPARK_SUBMIT_ARGS: '--packages com.datastax.spark:spark-cassandra-connector_2.12:2.5.2 --conf spark.cassandra.connection.host=dse pyspark-shell'
    links:
      - dse
  studio:  # Web interface for the Apache Cassandra and DataStax Enterprise
    image: datastax/dse-studio:6.8.1
    volumes:
      - ./dse-studio/connections:/var/lib/datastax-studio/connections/admin
      - ./dse-studio/notebooks:/opt/datastax-studio/examples/notebooks
    ports:
      - "9091:9091" # Exposes port to be available externally
    environment:
      DS_LICENSE: accept # Accept licence on start
      CLUSTER_NAME: Fontys
    links:
      - dse
  opscenter:
    image: datastax/dse-opscenter:6.8.0
    ports:
      - 8889:8888
    environment:
      DS_LICENSE: accept
      CLUSTER_NAME: Fontys
